#include <iostream>
#include <fstream>
using namespace std;

int main()
{
    int rows, cols;
    string value;
    ofstream file("table.html");
    cout << "Enter the number of rows :";
    cin >> rows;
    cout << "Enter the number of columns :";
    cin >> cols;
    file << "<!DOCTYPE html/>\n<html>\n <head>\n\t<title>\n\t\tTable\n\t</title>\n<style>table{font-family: sans-serif; border: 2px solid black; margin: auto;  text-align: center; width: 50%; height: 50%; border-collapse: collapse;} body{margin:auto; padding: 15px;} th,td {border: 1px solid black; padding: 5px} tr:nth-child(odd) {background-color: #D6EEEE;} </style></head>";
    file << "<body><h1 style=\"text-align: center; font-family: sans-serif; margin-top: 50px\">Table is generated by C++ code</h1><table>";
    for (int i = 0; i < rows; i++)
    {
        file << "<tr>";
        for (int j = 0; j < cols; j++)
        {
            if (i == 0)
            {
                cout << "Enter the name of column " << j + 1 << " : ";
                cin >> value;
                file << "<th> " << value << "</th>";
            }
            else
            {
                cout << "Enter the value of row " << i + 1 << " and column " << j + 1 << " :";
                cin >> value;
                file << "<td>" << value << "</td>";
            }
        }
        file << "</tr>";
    }
    file << "</table></body></html>\n";
    file.close();
    return 0;
}