CREATE TABLE PERSON (
    PERSON_ID VARCHAR(15) NOT NULL ,
    FIRST_NAME VARCHAR(20) NOT NULL ,
    LAST_NAME VARCHAR(20),
    EMAIL VARCHAR(40)  NOT NULL ,
    PHONE_NO VARCHAR(20) NOT NULL ,
    GENDER CHAR(1) NOT NULL ,
    CITY VARCHAR(85) NOT NULL ,
    STATE VARCHAR(2) NOT NULL ,
    POSTAL_CODE VARCHAR(10) NOT NULL ,
    COUNTRY VARCHAR(50) NOT NULL ,
    ROLE VARCHAR(10) NOT NULL ,
    PASSWORD VARCHAR(20) NOT NULL ,
    CONSTRAINT PERSON_ID_FORMAT_CHECK CHECK (PERSON_ID LIKE '[0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9]') ,
    CONSTRAINT PERSON_PK PRIMARY KEY (PERSON_ID) 
);

CREATE TABLE ARTIST (
    ARTIST_ID VARCHAR(15) NOT NULL ,
    STYLE VARCHAR(100) NOT NULL ,
    CONSTRAINT ARTIST_PK PRIMARY KEY (ARTIST_ID) ,
    CONSTRAINT FK_ARTIST_PERSON FOREIGN KEY (ARTIST_ID) REFERENCES PERSON (PERSON_ID) 
);

CREATE TABLE ARTWORK (
    ARTWORK_ID VARCHAR(15) NOT NULL ,
    TITLE VARCHAR(100) NOT NULL ,
    CATEGORY VARCHAR(50) NOT NULL ,
    ARTIST_ID VARCHAR(15) NOT NULL ,
    STOCKED_DATE DATE NOT NULL ,
    STATUS VARCHAR(20) NOT NULL ,
    IMAGE BLOB,
    CONSTRAINT ARTWORK_PK PRIMARY KEY (ARTWORK_ID) ,
    CONSTRAINT FK_ARTWORK_ARTIST FOREIGN KEY (ARTIST_ID) REFERENCES ARTIST (ARTIST_ID) 
);

CREATE TABLE ARTWORK_PRICE (
    ARTWORK_ID VARCHAR(15) NOT NULL ,
    PRICE DECIMAL(10,2) NOT NULL ,
    EFFECTIVE_DATE DATE NOT NULL ,
    CONSTRAINT ARTWORK_PRICE_PK PRIMARY KEY (ARTWORK_ID, EFFECTIVE_DATE) ,
    CONSTRAINT FK_ARTWORK FOREIGN KEY (ARTWORK_ID) REFERENCES ARTWORK (ARTWORK_ID) 
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID VARCHAR(15) NOT NULL ,
    ACCOUNT_CREATION_DATE DATE,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID) ,
    CONSTRAINT FK_CUSTOMER_PERSON FOREIGN KEY (CUSTOMER_ID) REFERENCES PERSON (PERSON_ID) 
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID VARCHAR(15) NOT NULL ,
    ROLE VARCHAR(50) NOT NULL ,
    SALARY DECIMAL(8,2) NOT NULL ,
    STATUS VARCHAR(20) NOT NULL ,
    JOINING_DATE DATE NOT NULL ,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID) ,
    CONSTRAINT FK_EMPLOYEE_PERSON FOREIGN KEY (EMPLOYEE_ID) REFERENCES PERSON (PERSON_ID) 
);

CREATE TABLE EVENT (
    EVENT_NAME VARCHAR(50) NOT NULL ,
    START_DATE DATE NOT NULL ,
    END_DATE DATE NOT NULL ,
    EVENT_LOCATION VARCHAR(100) NOT NULL ,
    EMPLOYEE_ID VARCHAR(15) NOT NULL ,
    CONSTRAINT EVENT_PK PRIMARY KEY (EVENT_NAME, START_DATE) ,
	--FK_EVENT_ARTIST i think its unnessary but don't change it untill there is no error
    CONSTRAINT FK_EVENT_ARTIST FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID) 
);

CREATE TABLE EVENT_ARTWORK (
    EVENT_NAME VARCHAR(50) NOT NULL ,
    START_DATE DATE NOT NULL ,
    ARTWORK_ID VARCHAR(15) NOT NULL ,
    CONSTRAINT EVENT_ARTWORK_PK PRIMARY KEY (EVENT_NAME, ARTWORK_ID, START_DATE) ,
    CONSTRAINT FK_EVENT_ARTWORK1 FOREIGN KEY (EVENT_NAME, START_DATE) REFERENCES EVENT (EVENT_NAME, START_DATE) ,
    CONSTRAINT FK_EVENT_ARTWORK2 FOREIGN KEY (ARTWORK_ID) REFERENCES ARTWORK (ARTWORK_ID) 
);

CREATE TABLE EVENT_EMPLOYEE (
    EVENT_NAME VARCHAR(50) NOT NULL ,
    START_DATE DATE NOT NULL ,
    EMPLOYEE_ID VARCHAR(15) NOT NULL ,
    WORK_HOURS DECIMAL(2,0) NOT NULL ,
    EVENT_ROLE VARCHAR(50) NOT NULL ,
    CONSTRAINT EVENT_EMPLOYEE_PK PRIMARY KEY (EVENT_NAME, EMPLOYEE_ID, START_DATE) ,
    CONSTRAINT FK_TICKET_EVENT1 FOREIGN KEY (EVENT_NAME, START_DATE) REFERENCES EVENT (EVENT_NAME, START_DATE) ,
    CONSTRAINT FK_TICKET_EVENT2 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID) 
);

CREATE TABLE ORDER_T (
    ORDER_ID VARCHAR(15) NOT NULL ,
    CUSTOMER_ID VARCHAR(15) NOT NULL ,
    RECIPIENT VARCHAR(50) NOT NULL ,
    ORDER_DATE DATE NOT NULL ,
    ORDER_STATUS VARCHAR(20) NOT NULL ,
    PAYMENT_METHOD VARCHAR(20) NOT NULL ,
    CONSTRAINT ORDER_PK PRIMARY KEY (ORDER_ID) ,
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) 
);

CREATE TABLE ORDERLINE (
    ORDER_ID VARCHAR(15) NOT NULL ,
    ARTWORK_ID VARCHAR(15) NOT NULL ,
    CONSTRAINT ORDERLINE_PK PRIMARY KEY (ORDER_ID, ARTWORK_ID) ,
    CONSTRAINT FK_ORDERLINE_ARTWORK FOREIGN KEY (ARTWORK_ID) REFERENCES ARTWORK (ARTWORK_ID) ,
    CONSTRAINT FK_ORDERLINE_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDER_T (ORDER_ID) 
);

CREATE TABLE TICKET (
    EVENT_NAME VARCHAR(50) NOT NULL ,
    START_DATE DATE NOT NULL ,
    TICKET_PRICE DECIMAL(5,0) NOT NULL ,
    EFFECTIVE_DATE DATE NOT NULL ,
    CONSTRAINT TICKET_PK PRIMARY KEY (EVENT_NAME, START_DATE, TICKET_PRICE) ,
    CONSTRAINT FK_TICKET_EVENT FOREIGN KEY (EVENT_NAME, START_DATE) REFERENCES EVENT (EVENT_NAME, START_DATE) 
);

